name: shopease
description: ShopEase flutter application
version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  http_mock_adapter: ^0.6.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: 26fedcee4b0e6f7a85f65f1fb48834a21f57e970

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/png/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - animations/
    - images/svg/
    - images/png/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.4.3+1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  currency_text_input_formatter: ^2.1.7
  google_fonts: 6.1.0
  device_info_plus: ^9.0.2
  page_transition: ^2.0.9
  device_preview: ^1.2.0
  flutter_screenutil: ^5.6.1
  intl: ^0.19.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_local_notifications: ^17.0.1
  super_tooltip: ^2.0.7
  gauge_indicator: ^0.4.3
  omni_datetime_picker: ^1.0.9
  flutter_udid: ^3.0.0
  pinput: ^4.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  badges: ^3.1.2
  another_flushbar: ^1.12.30
  intl_phone_field: ^3.1.0
  image_picker: ^1.1.2
  image_cropper: ^5.0.1
  fl_country_code_picker: ^0.1.9+1
  url_launcher: ^6.3.1
  email_validator: ^2.1.17
  flutter_pdfview: ^1.3.2
  flutter_datetime_picker_plus: ^2.1.0
  file_picker: ^8.0.0+1
  open_filex: ^4.3.2
  package_info_plus: ^4.2.0
  path_provider: ^2.1.2
  path: ^1.8.3
  timezone: ^0.9.3
  web_socket_channel: ^2.4.0
  change_app_package_name: ^1.4.0
  smooth_page_indicator: ^1.2.0+3
  flutter_vibrate: ^1.3.0
  flutter_cache_manager: ^3.4.1
  timeago: ^3.6.1
  pull_to_refresh_flutter3: ^2.0.2
  flutter_switch: ^0.3.2
  dotted_border: ^2.1.0
  flutter_image_compress: ^2.1.0
  qr_flutter: ^4.1.0
  share_plus: ^7.0.0
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  app_links: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  grouped_list: ^6.0.0
  qr_code_scanner_plus: ^2.0.6
  mixpanel_flutter: ^2.3.3
  country_codes: ^3.1.0+2
  store_redirect: ^2.0.2
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  pretty_qr_code: ^3.3.0
  flip_card: ^0.7.0
  confetti: ^0.8.0

  #Firebase
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_database: ^11.1.6
  firebase_analytics: ^11.3.5

